from source.constants import *
import sys,os


ROOT_DIR=ROOT_DIR_KEY

# dataset path

DATASET_PATH=os.path.join(ROOT_DIR,DATA_DIR,DATA_DIR_KEY)


# raw file path

RAW_FILE_PATH= os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,
                            DATA_INGESTION_KEY,CURRENT_TIME_STAMP,DATA_INGESTION_KEY_RAW_DATA_DIR,RAW_DATA_DIR_KEY)

# train and test file path
TRAIN_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_INGESTION_KEY,CURRENT_TIME_STAMP,
                             DATA_INGESTION_INGESTED_DATA_DIR_KEY,TRAIN_DATA_DIR_KEY)


TEST_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_INGESTION_KEY,CURRENT_TIME_STAMP,DATA_INGESTION_INGESTED_DATA_DIR_KEY,
                            TEST_DATA_DIR_KEY)

######## DATA TRANSFORMATION #######

PREPROCESSING_OBJ_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFORMATION_ARTIFACT,DATA_PREPROCESS_DIR,DATA_PREPROCESS_OBJ)

TRANSFORM_TRAIN_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFORMATION_ARTIFACT,
                                       DATA_TRANSFORMATION_DIR,TRANSFORM_TRAIN_KEY)

TRANSFORM_TEST_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFORMATION_ARTIFACT,
                                      DATA_TRANSFORMATION_DIR,TRANSFORM_TEST_KEY)

FEATURE_ENGG_OBJ_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFORMATION_ARTIFACT,
                                        DATA_PREPROCESS_DIR,'feature_engg.pkl')


# model file path
MODEL_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,MODEL_TRAINER_KEY,MODEL_OBJECT)